appFlask/lessons/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, FileField
from wtforms_sqlalchemy.fields import QuerySelectField
from flask_ckeditor import CKEditorField
from wtforms.validators import DataRequired, Length
from appFlask.models import Course

def choice_query():
    return Course.query.all()  # Ensuring it returns a list, not a query object


class NewLessonForm(FlaskForm):
    course = QuerySelectField("Course", query_factory=choice_query, get_label="title")
    title = StringField("Lesson Title", validators=[DataRequired(), Length(max=100)])
    slug = StringField(
        "Slug",
        validators=[DataRequired(), Length(max=32)],
        render_kw={
            "placeholder": "Descriptive short version of your title. SEO friendly"
        },
    )
    content = CKEditorField(
        "Lesson Content", validators=[DataRequired()], render_kw={"rows": "20"}
    )
    thumbnail = FileField(
        "Thumbnail", validators=[DataRequired(), FileAllowed(["jpg", "png"])]
    )
    submit = SubmitField("Post")

class LessonUpdateForm(NewLessonForm):
    thumbnail = FileField("Thumbnail", validators=[FileAllowed(["jpg", "png"])])
    submit = SubmitField("Update")

appFlask/courses/routes.py
from flask import Blueprint
from appFlask.models import Lesson , Course
from flask import render_template , request


courses_bp =  Blueprint('courses',__name__)


@courses_bp.route("/<string:course_title>") ## dynamic link
def course(course_title):
    course = Course.query.filter_by(title = course_title).first()
    course_id = course.id if course else None
    course = Course.query.get_or_404(course_id) 
    page = request.args.get('page',1,type=int)
    lessons = Lesson.query.filter_by(course_id=course_id).paginate(page=page,per_page=6)
    return render_template('course.html',title=course.title,course=course,lessons=lessons)

@courses_bp.route("/courses") 
def courses():
    page = request.args.get('page',1,type=int)
    courses = Course.query.paginate(page = page,per_page=6)
    return render_template('courses.html', title = "Courses" , courses=courses)

appFlask/lessons/routes.py
from flask import Blueprint
from appFlask.models import Lesson , Course
from flask import render_template , url_for,flash,redirect,request,session
from appFlask.lessons.forms import NewLessonForm,LessonUpdateForm
from appFlask.courses.forms import NewCourseForm
from appFlask import db
from flask_modals import render_template_modal
from flask_login import current_user,login_required
from flask import abort
from appFlask.helpers import save_picture
from appFlask.lessons.helpers import get_previous_next_lesson ,delete_picture

lessons = Blueprint('lessons',__name__)


@lessons.route("/dashboard/new_lesson",methods=["GET","POST"])
@login_required
def new_lesson():
    new_lesson_form = NewLessonForm()
    new_course_form = NewCourseForm()
    flag = session.pop('flag',False)
    ## to know the request is from which form , i depend on the special coulmns in each form
    form =''
    if 'slug' in request.form:
        form = 'new_lesson_form'
    elif 'description' in request.form:
        form = 'new_course_form'
    if form == 'new_lesson_form' and new_lesson_form.validate_on_submit():
         if new_lesson_form.thumbnail.data:
            picture_file = save_picture(new_lesson_form.thumbnail.data,'static/lesson_thumbnails')
         lesson_slug = str(new_lesson_form.slug.data).replace(" ","-")
         course = new_lesson_form.course.data
         lesson = Lesson(
             title = new_lesson_form.title.data,
             content = new_lesson_form.content.data,
             slug = lesson_slug ,
             author = current_user,
             course_name = course,
             thumbnail = picture_file
         )
         db.session.add(lesson)
         db.session.commit()
         flash('Your lesson has been created!','success')
         return redirect(url_for('main.home'))
    elif form == 'new_course_form' and new_course_form.validate_on_submit():
        if new_course_form.icon.data:
            picture_file = save_picture(new_course_form.icon.data,'static/course_icon',output_size=(150,150))
        course_title = str(new_course_form.title.data).replace(" ","-")
        course = Course(
            title = course_title,
            description = new_course_form.description.data,
            icon = picture_file
        )
        db.session.add(course)
        db.session.commit()
        session['flag']=True
        flash('New course has been created!','success')
        return redirect(url_for('users.dashboard'))
    modal = None if flag else 'newCourse' ## to know if we wll call the modal
    return render_template_modal(
        'new_lesson.html',
        title = 'New_Lesson',
        new_lesson_form=new_lesson_form,
        new_course_form=new_course_form,
        active_tab="new_lesson",
        modal = modal)

@lessons.route("/<string:course>/<string:lesson_slug>") ## dynamic link
def lesson(lesson_slug,course):
    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id) ## it will check in db if didn't find the lesson it will return http request 404 'NOT found'
    return render_template('lesson_view.html',title=lesson.title,lesson=lesson, previous_lesson=previous_lesson,
        next_lesson=next_lesson,)


@lessons.route("/dashboard/user_lessons", methods=["GET", "POST"])
@login_required
def user_lessons():
    return render_template(
        "user_lessons.html", title="Your Lessons", active_tab="user_lessons"
    )

@lessons.route("/<string:course>/<string:lesson_slug>/update", methods=["GET", "POST"])
def update_lesson(lesson_slug, course):
    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)
    form = LessonUpdateForm()
    if form.validate_on_submit():
        lesson.course_name = form.course.data
        lesson.title = form.title.data
        lesson.slug = str(form.slug.data).replace(" ", "-")
        lesson.content = form.content.data
        if form.thumbnail.data:
            delete_picture(lesson.thumbnail, "static/lesson_thumbnails")
            new_picture = save_picture(form.thumbnail.data, "static/lesson_thumbnails")
            lesson.thumbnail = new_picture
        db.session.commit()
        flash("Your lesson has been updated!", "success")
        return redirect(
            url_for("lessons.lesson", lesson_slug=lesson.slug, course=lesson.course_name.title)
        )
    elif request.method == "GET":
        form.course.data = lesson.course_name.title
        form.title.data = lesson.title
        form.slug.data = lesson.slug
        form.content.data = lesson.content
    return render_template(
        "update_lesson.html",
        title="Update | " + lesson.title,
        lesson=lesson,
        previous_lesson=previous_lesson,
        next_lesson=next_lesson,
        form=form,
    )


@lessons.route("/lesson/<lesson_id>/delete", methods=["POST"])
def delete_lesson(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)
    db.session.delete(lesson)
    db.session.commit()
    flash("Your lesson has been deleted!", "success")
    return redirect(url_for("lessons.user_lessons"))

appFlask/main/routes.py
from flask import Blueprint
import secrets
from flask_ckeditor import upload_fail,upload_success
import os
from appFlask.models import Lesson , Course
from flask import render_template , url_for,request,send_from_directory


main = Blueprint('main',__name__)


## the down two methods from CKEDITOR Flask decomentaion
@main.route('/files/<path:filename>')
def uploaded_files(filename):
    path = os.path.join(main.root_path, 'static/media')
    return send_from_directory(path, filename)

@main.route('/upload', methods=['POST'])
def upload():
    f = request.files.get('upload')
    extension = f.filename.split('.')[-1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:
        return upload_fail(message='File extension not allowed!')
    random_hex = secrets.token_hex(8)
    image_name = random_hex+extension
    f.save(os.path.join(main.root_path, 'static/media', image_name))
    url = url_for('main.uploaded_files', filename=image_name)
    return upload_success(url, filename=image_name)


@main.route("/")
@main.route("/home")

def home():
     lessons = Lesson.query.order_by(Lesson.date_posted.desc()).paginate(page=1,per_page=6)
     courses = Course.query.paginate(page = 1,per_page=6)
     return render_template('home.html', lessons=lessons, courses=courses)

@main.route("/about")
def about():
    return render_template('about.html',title='About')

appFlask/users/routes.py
from flask import Blueprint
from appFlask.models import User, Lesson
from flask import render_template , url_for,flash,redirect,request
from appFlask.users.forms import RegistrationForm,LoginForm,UpdateProfileForm,RequestResetForm,ResetPasswordForm
from appFlask import bcrypt,db
from flask_login import login_user , current_user,logout_user,login_required
from appFlask.helpers import save_picture
from appFlask.users.helpers import send_reset_email

users = Blueprint('users',__name__)


@users.route("/register",methods=["GET","POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            fname=form.fname.data,
            lname = form.lname.data,
            username=form.username.data,
            email=form.email.data,
            password = hashed_password
            )
        db.session.add(user)
        db.session.commit()
        flash(f"Account created successfully for {form.username.data}", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)

@users.route("/login",methods=["GET","POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user, remember=form.remember.data) # it will create session
            next_page = request.args.get('next')
            flash('You have been logged in!', 'success')
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash('Login unSuccessfull, Please check credintial!', 'danger')

    return render_template('login.html',title='Login', form = form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("home"))

@users.route("/dashboard",methods=["GET"])
@login_required
def dashboard():
    return render_template('dashboard.html',title = 'Dashboard',active_tab="None")

@users.route("/dashboard/profile",methods=["GET","POST"])
@login_required
def profile():
    profile_form = UpdateProfileForm()
    if profile_form.validate_on_submit():
        if profile_form.picture.data:
            picture_file = save_picture(profile_form.picture.data,'static/user_pics', output_size =(150,150))
            current_user.image_file = picture_file
        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data
        current_user.bio = profile_form.bio.data
        db.session.commit()
        flash('Your profile updated successfully','success')
        return redirect(url_for('users.profile'))
    elif request.method == "GET":
        profile_form.username.data = current_user.username 
        profile_form.email.data = current_user.email 
        profile_form.bio.data = current_user.bio 
    image_file = url_for('static', filename = f'user_pics/{current_user.image_file}')
    return render_template('profile.html',title = 'Profile',profile_form=profile_form,image_file=image_file,active_tab="profile")


@users.route("/author/<string:username>", methods=["GET"])
def author(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    lessons = (
        Lesson.query.filter_by(author=user)
        .order_by(Lesson.date_posted.desc())
        .paginate(page=page, per_page=6)
    )
    return render_template('author.html', lessons=lessons, user=user)

@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash(
            "If this account exists, you will receive an email with instructions",
            "info",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if not user:
        flash("The token is invalid or expired", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated. You can now log in", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_password.html", title="Reset Password", form=form)

appFlask/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>about Page</h1>
{% endblock content%}

appFlask/templates/author.html
{% extends "layout.html"%}
{% block content %}
<!-- author image and bio -->
<div class="container-fluid bg-secondary">
    <div class="container">
        <div class="row p-5">
            <div class="col-6">
                <img class="rounded-circle" src="{{url_for('static', filename='user_pics/' + user.image_file)}}" alt="">
            </div>
            <div class="col-6">
                <span class="lead text-light">{{user.bio}}</span>
            </div>
        </div>
    </div>
</div>
<section class="bg-light">
    <div class="container p-5">
        <div class="row mb-5 ">
        </div>
        <div class="row">
            {% for lesson in lessons.items %}
            <div class="col-sm-12 col-md-6 col-lg-4 pb-5 d-flex align-items-stretch">
                <div class="card lesson">
                    <img src="{{url_for('static', filename='lesson_thumbnails/'+lesson.thumbnail)}}" class="card-img">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">
                            <a class="text-decoration-none text-dark"
                                href="{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}">{{lesson.title}}</a>
                        </h5>
                        <p class="card-text mb-0">In:
                            <a href="{{url_for('courses.course', course_title=lesson.course_name.title)}}"
                                class="link">{{lesson.course_name.title}}</a>
                        </p>
                        <span class="text-muted">On: {{lesson.date_posted.strftime('%Y-%m-%d')}}</span>

                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- pagination links -->
            <nav class="mt-5" aria-label="...">
                <ul class="pagination" style="display: flex; justify-content: flex-end">
                    {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                    {% if lessons.page == page_num %}
                    <li class="page-item active">
                        <a href="{{url_for('users.author', username=user.username, page=page_num)}}"
                            class="page-link">{{page_num}}</a>
                    </li>
                    {%else%}
                    <li class="page-item">
                        <a href="{{url_for('users.author', username=user.username, page=page_num)}}"
                            class="page-link">{{page_num}}</a>
                    </li>
                    {%endif%}
                    {% else %}
                    <span class="mx-2">...</span>
                    {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</section>

{% endblock content%}

appFlask/templates/courses.html
{% extends "layout.html"%}
{% block content %}

<section class="bg-ligh">
    <div class="container p-5">
        <h3 class="text-center text-secondary" id='learn'>Courses</h3>
        <div class="row">
            {% for course in courses.items %}
            <div class="col-sm-12 col-md-6 col-lg-4 p-3 d-flex align-items-stretch">
                <a href="{{url_for('courses.course', course_title=course.title)}}" class="text-decoration-none">
                    <div class="card bg-dark text-light h-100">
                        <div class="card-body text-center">
                            <img src="{{url_for('static', filename='course_icon/'+course.icon)}}" alt=""
                                class="card-img w-25">
                            <h4 class="card-title mb-3">
                                {{course.title}}
                            </h4>
                            <p class="card-text">{{course.description}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
            <!-- pagination links -->
            <nav class="mt-5" aria-label="...">
                <ul class="pagination" style="display: flex; justify-content: flex-end">
                    {% for page_num in courses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                    {% if courses.page == page_num %}
                    <li class="page-item active">
                        <a href="{{url_for('courses.courses', page=page_num)}}" class="page-link">{{page_num}}</a>
                    </li>
                    {%else%}
                    <li class="page-item">
                        <a href="{{url_for('courses.courses', page=page_num)}}" class="page-link">{{page_num}}</a>
                    </li>
                    {%endif%}
                    {% else %}
                    ...
                    {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</section>

{% endblock content %}

appFlask/templates/home.html
{% extends "layout.html" %}
{% block content %}
<section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
            <div>
                <h1 class="mb-10"> Learn <span class="text-warning"> To Code</span></h1>
                <p class="lead my-4">
                    We focus on teaching programming in an intuitive and easy to follow way. All you need is
                    dedication!
                </p>
                <a class="btn btn-danger btn-lg border"
                    href="https://www.youtube.com/channel/UCEsvQ6d7qsnOSNXtccIzScQ?sub_confirmation=1" target="_blank">
                    <i class="bi bi-youtube m-3"></i>Subscribe
                </a>

            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{{url_for('static', filename='showcase.svg')}}" alt="">
        </div>
    </div>
</section>

<!-- Social Media -->
<section class="bg-primary text-light p-5">
    <div class="container">
        <div class="d-md-flex justify-content-between align-items-center">
            <h3 class="mb-3 text-center">Join Our Community</h3>
            <nav class="navbar navbar-expand-lg navbar-dark">
                <button class="navbar-toggler border" type="button" data-bs-toggle="collapse"
                    data-bs-target="#socialbtn">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="socialbtn">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="btn btn-dark ms-5 button_width" href="https://github.com/omar-ghoneim"
                                target="_blank">
                                <i class="bi-github" role="img"></i>
                                GitHub
                            </a>
                        </li>
                        <li>
                            <a class="btn btn-dark ms-5 button_width" href="https://www.facebook.com/Pythonic88"
                                target="_blank">
                                <i class="bi bi-facebook "></i>
                                Facebook
                            </a>
                        </li>
                        <li class="nav-item">
                            <a type="button" class="btn btn-dark ms-5 button_width"
                                href="https://www.instagram.com/pythonic_88" target="_blank">
                                <i class="bi bi-instagram"></i>
                                Instagram
                            </a>

                        </li>
                        <li class="nav-item">
                            <a class="btn btn-dark ms-5 button_width" href="https://twitter.com/Pythonic88"
                                target="_blank">
                                <i class="bi bi-twitter"></i>
                                Twitter
                            </a>

                        </li>
                        <li class="nav-item">
                            <a class="btn btn-dark ms-5 button_width" href="https://www.tiktok.com/@pythonic88"
                                target="_blank">
                                <i class="bi bi-tiktok"></i>
                                TikTok
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

    </div>
    </div>
</section>
<!-- Courses -->
<section class="bg-ligh">
    <div class="container p-5">
        <h3 class="text-center text-secondary" id='learn'>Courses</h3>
        <div class="row">
            {% for course in courses.items %}
    <div class="col-sm-12 col-md-6 col-lg-4 p-3 d-flex align-items-stretch">
        <a href="{{url_for('courses.course', course_title=course.title)}}" class="text-decoration-none">
            <div class="card bg-dark text-light h-100">
                <div class="card-body text-center">
                    <img src="{{ url_for('static', filename='course_icon/'+course.icon) }}" alt="" class="card-img w-25">
                    <h4 class="card-title mb-3">
                        {{ course.title }}
                    </h4>
                    <p class="card-text">{{ course.description }}</p>
                </div>
            </div>
        </a>
    </div>
{% endfor %}

        </div>
         <!-- more courses -->
         <div class="" style="display: flex; justify-content: flex-end">
            <a href="{{ url_for('courses.courses')}}" class="btn btn-info btn-lg"> More Courses &gt&gt&gt</a>
        </div>
    </div>
</section>
    <!-- Lessons -->
<section class="bg-dark">
    <div class="container p-5">
        <div class="row mb-5 ">
            <div class="col">
                <h3 class="text-uppercase text-center text-light">latest lessons</h3>
            </div>
        </div>
        <div class="row">
            {% for lesson in lessons.items %}
            <div class="col-sm-12 col-md-6 col-lg-4 pb-5 d-flex align-items-stretch">
                <div class="card lesson">
                    <img src="{{url_for('static', filename='lesson_thumbnails/'+lesson.thumbnail)}}" class="card-img">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">
                            <a class="text-decoration-none text-dark" href="{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}">{{lesson.title}}</a>
                        </h5>
                        <p class="card-text mb-0">In:
                            <a class="text-decoration-none" href="{{url_for('courses.course',course_title=lesson.course_name.title)}}">{{lesson.course_name.title}}</a>
                        </p>
                        <span><img class="article-img rounded-circle" src="{{url_for('static', filename='user_pics/'+lesson.author.image_file)}}" alt="">By: <a
                                href="{{url_for('users.author',username=lesson.author.username )}}" class="link">{{lesson.author.username}}</a></span>
                                <div class="span text-muted">
                                    On: {{lesson.date_posted.strftime('%Y-%m-%d')}}
                                </div>

                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

{% endblock content%}

appFlask/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title  %}
    <title>Flask - {{title}}</title>
    {% else %}
    <title>Flask</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    {{modals()}}
    {{ ckeditor.load_code_theme() }}
</head>
<body class="d-flex flex-column min-vh-100">
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
    <div class="container">
        <a href="{{url_for('main.home')}}" class="navbar-brand">Flask</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{url_for('main.about')}}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    {% if request.path=='/home' %}
                    <a href="#learn" class="nav-link">Start Learning</a>
                    {% else %}
                    <a href="{{url_for('courses.courses')}}" class="nav-link">Start Learning</a>
                    {% endif %}
                </li>
            </ul>
            <!-- User Links -->
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                <div class="dropdown show">
                    <button class="btn btn-dark bg-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                      My Account
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{{url_for('users.dashboard')}}" >Dashboard</a></li>
                      <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a></li>
                    </ul>
                  </div>
                {% else %}
                <li class="nav-item">
                    <a href="{{url_for('users.register')}}" class="nav-link">Register</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('users.login')}}"  class="nav-link">Login</a>
                </li>
                
                {% endif %}
               
            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center">
        {{message}}
    </div>
    {% endfor %}

    {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
<!-- footer -->

<footer class="bg-dark mt-auto">
    <div class="container p-3">
        <div class="row text-center text-white">
            <div class="col-md-12 col-lg-4 pb-2">
                <h4 class="text-center text-decoration-underline">Quick Links</h4>
                <ul class=" nobull pt-3">
                    <li><a href="#" class="link text-white">Privacy Policy</a></li>
                    <li><a href="#" class="link text-white">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="col-md-12 col-lg-4">
                <h4 class="text-center text-decoration-underline pb-3">Social Links</h4>
                <a href="#" class="text-white p-2"><i class="bi-github"></i></a>
                <a href="#" class="text-white p-2"><i class="bi-youtube"></i></a>
                <a href="#" class="text-white p-2"><i class="bi-facebook"></i></a>
                <a href="#" class="text-white p-2"><i class="bi-twitter"></i></a>
                <a href="#" class="text-white p-2"><i class="bi-instagram"></i></a>
                <a href="#" class="text-white p-2"><i class="bi-tiktok"></i></a>

            </div>
            <div class="col-md-12 col-lg-4 pb-2">
                <h4 class="text-center text-decoration-underline pb-3">Contact Us</h4>
                <p class="lead">Anoud.1466@gmail.com</p>
            </div>
        </div>
        <div class="col text-white text-center position-relative">
            <p class="lead font-weight-bold">Copyright &copy; 2024 | Flask</p>
            <a href="#" class="position-absolute bottom-0 end-0">
                <i class="bi bi-arrow-up-circle h1"></i>
            </a>
        </div>
    </div>

</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"></script>
</body>
</html>